server:
  port: 9101
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///test01
    username: postgres
    password: root
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
  banner:
    location: banner/banner.txt
logging:
  config: classpath:log4j2-spring.xml
  level:
    root: trace
    #操他妈的 还真是这里要加一个root

#        naming:
#          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#           这个是无修改命名
#          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#           这个是遇到大些字母添加'_'