server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test01?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: classpath*:/mapper/*.xml 这个是mapper.xml配置我估计不需要啊
  type-aliases-package: com.mybatis.pojo  #设置包扫描路径
  #这个写上 是将字段有-的自动转化为驼峰命名法
# 引用mybatis的相关配置 这个是默认的配置可以去掉引号