package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbAreas;

public interface TbAreasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_areas
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbAreas selectByPrimaryKey(Integer id);
}