package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbCities;

public interface TbCitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbCities selectByPrimaryKey(Integer id);
}