package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbContentCategory;

public interface TbContentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbContentCategory selectByPrimaryKey(Long id);
}