package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbContent;

public interface TbContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbContent selectByPrimaryKey(Long id);
}