package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbFreightTemplate;

public interface TbFreightTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight_template
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbFreightTemplate selectByPrimaryKey(Long id);
}