package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbOrder;

public interface TbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbOrder selectByPrimaryKey(Long orderId);
}