package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbOrderItem;

public interface TbOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_item
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbOrderItem selectByPrimaryKey(Long id);
}