package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbPayLog;

public interface TbPayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay_log
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbPayLog selectByPrimaryKey(String outTradeNo);
}