package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbProvinces;

public interface TbProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_provinces
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbProvinces selectByPrimaryKey(Integer id);
}