package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbSeckillGoods;

public interface TbSeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_goods
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbSeckillGoods selectByPrimaryKey(Long id);
}