package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbSeckillOrder;

public interface TbSeckillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seckill_order
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbSeckillOrder selectByPrimaryKey(Long id);
}