package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbSeller;

public interface TbSellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbSeller selectByPrimaryKey(String sellerId);

    String selectNameBySellerId(String sellerId);
}