package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbSpecificationOption;

public interface TbSpecificationOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specification_option
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbSpecificationOption selectByPrimaryKey(Long id);
}