package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbSpecification;

public interface TbSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_specification
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbSpecification selectByPrimaryKey(Long id);
}