package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.demo.swaggerdemo.entity.TbTypeTemplate;

public interface TbTypeTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type_template
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbTypeTemplate selectByPrimaryKey(Long id);
}