package com.springboot.demo.swaggerdemo.mapper;

import com.springboot.common.context.UserContext;
import com.springboot.demo.swaggerdemo.entity.TbUser;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    TbUser selectByPrimaryKey(Long id);

    //
    int updateUser(UserContext userContext);
}