package com.springboot.demo.swaggerdemo.entity;

import com.springboot.demo.swaggerdemo.annotation.Mobile;
import lombok.ToString;

import java.util.Date;

@ToString
public class TbSeller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.seller_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.nick_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.password
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.email
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.mobile
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.telephone
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.status
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.address_detail
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String addressDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.linkman_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String linkmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.linkman_qq
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String linkmanQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.linkman_mobile
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String linkmanMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.linkman_email
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String linkmanEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.license_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String licenseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.tax_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String taxNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.org_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String orgNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.address
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private Long address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.logo_pic
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String logoPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.brief
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.create_time
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.legal_person
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.legal_person_card_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String legalPersonCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.bank_user
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String bankUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_seller.bank_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String bankName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.seller_id
     *
     * @return the value of tb_seller.seller_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.seller_id
     *
     * @param sellerId the value for tb_seller.seller_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.name
     *
     * @return the value of tb_seller.name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.name
     *
     * @param name the value for tb_seller.name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.nick_name
     *
     * @return the value of tb_seller.nick_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.nick_name
     *
     * @param nickName the value for tb_seller.nick_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.password
     *
     * @return the value of tb_seller.password
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.password
     *
     * @param password the value for tb_seller.password
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.email
     *
     * @return the value of tb_seller.email
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.email
     *
     * @param email the value for tb_seller.email
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.mobile
     *
     * @return the value of tb_seller.mobile
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.mobile
     *
     * @param mobile the value for tb_seller.mobile
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.telephone
     *
     * @return the value of tb_seller.telephone
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.telephone
     *
     * @param telephone the value for tb_seller.telephone
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.status
     *
     * @return the value of tb_seller.status
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.status
     *
     * @param status the value for tb_seller.status
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.address_detail
     *
     * @return the value of tb_seller.address_detail
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.address_detail
     *
     * @param addressDetail the value for tb_seller.address_detail
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.linkman_name
     *
     * @return the value of tb_seller.linkman_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLinkmanName() {
        return linkmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.linkman_name
     *
     * @param linkmanName the value for tb_seller.linkman_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLinkmanName(String linkmanName) {
        this.linkmanName = linkmanName == null ? null : linkmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.linkman_qq
     *
     * @return the value of tb_seller.linkman_qq
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLinkmanQq() {
        return linkmanQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.linkman_qq
     *
     * @param linkmanQq the value for tb_seller.linkman_qq
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLinkmanQq(String linkmanQq) {
        this.linkmanQq = linkmanQq == null ? null : linkmanQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.linkman_mobile
     *
     * @return the value of tb_seller.linkman_mobile
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLinkmanMobile() {
        return linkmanMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.linkman_mobile
     *
     * @param linkmanMobile the value for tb_seller.linkman_mobile
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLinkmanMobile(String linkmanMobile) {
        this.linkmanMobile = linkmanMobile == null ? null : linkmanMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.linkman_email
     *
     * @return the value of tb_seller.linkman_email
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLinkmanEmail() {
        return linkmanEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.linkman_email
     *
     * @param linkmanEmail the value for tb_seller.linkman_email
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLinkmanEmail(String linkmanEmail) {
        this.linkmanEmail = linkmanEmail == null ? null : linkmanEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.license_number
     *
     * @return the value of tb_seller.license_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.license_number
     *
     * @param licenseNumber the value for tb_seller.license_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.tax_number
     *
     * @return the value of tb_seller.tax_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.tax_number
     *
     * @param taxNumber the value for tb_seller.tax_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber == null ? null : taxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.org_number
     *
     * @return the value of tb_seller.org_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getOrgNumber() {
        return orgNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.org_number
     *
     * @param orgNumber the value for tb_seller.org_number
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setOrgNumber(String orgNumber) {
        this.orgNumber = orgNumber == null ? null : orgNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.address
     *
     * @return the value of tb_seller.address
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public Long getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.address
     *
     * @param address the value for tb_seller.address
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setAddress(Long address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.logo_pic
     *
     * @return the value of tb_seller.logo_pic
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLogoPic() {
        return logoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.logo_pic
     *
     * @param logoPic the value for tb_seller.logo_pic
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLogoPic(String logoPic) {
        this.logoPic = logoPic == null ? null : logoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.brief
     *
     * @return the value of tb_seller.brief
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.brief
     *
     * @param brief the value for tb_seller.brief
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.create_time
     *
     * @return the value of tb_seller.create_time
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.create_time
     *
     * @param createTime the value for tb_seller.create_time
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.legal_person
     *
     * @return the value of tb_seller.legal_person
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.legal_person
     *
     * @param legalPerson the value for tb_seller.legal_person
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.legal_person_card_id
     *
     * @return the value of tb_seller.legal_person_card_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getLegalPersonCardId() {
        return legalPersonCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.legal_person_card_id
     *
     * @param legalPersonCardId the value for tb_seller.legal_person_card_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setLegalPersonCardId(String legalPersonCardId) {
        this.legalPersonCardId = legalPersonCardId == null ? null : legalPersonCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.bank_user
     *
     * @return the value of tb_seller.bank_user
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.bank_user
     *
     * @param bankUser the value for tb_seller.bank_user
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_seller.bank_name
     *
     * @return the value of tb_seller.bank_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_seller.bank_name
     *
     * @param bankName the value for tb_seller.bank_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }
}