package com.springboot.demo.swaggerdemo.entity;

public class TbSpecificationOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specification_option.id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specification_option.option_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private String optionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specification_option.spec_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private Long specId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_specification_option.orders
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    private Integer orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specification_option.id
     *
     * @return the value of tb_specification_option.id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specification_option.id
     *
     * @param id the value for tb_specification_option.id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specification_option.option_name
     *
     * @return the value of tb_specification_option.option_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specification_option.option_name
     *
     * @param optionName the value for tb_specification_option.option_name
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specification_option.spec_id
     *
     * @return the value of tb_specification_option.spec_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public Long getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specification_option.spec_id
     *
     * @param specId the value for tb_specification_option.spec_id
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setSpecId(Long specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_specification_option.orders
     *
     * @return the value of tb_specification_option.orders
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_specification_option.orders
     *
     * @param orders the value for tb_specification_option.orders
     *
     * @mbg.generated Sat May 16 14:11:45 CST 2020
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }
}